security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    # ...
    providers:
        my_entity_provider:
            entity:
                class: App\Entity\User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: my_entity_provider
    # ...